export default [
  {
    id: 1,
    name: 'alignContent',
    options: ['stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around'],
  },
  { id: 2, name: 'alignItems', options: ['stretch', 'center', 'flex-start', 'flex-end', 'baseline'] },
  {
    id: 3,
    name: 'alignSelf',
    options: ['auto', 'stretch', 'center', 'flex-start', 'flex-end', 'baseline'],
  },
  { id: 4, name: 'animationDelay', options: ['value'] },
  { id: 5, name: 'animationDirection', options: ['normal', 'reverse', 'alternate', 'alternate-reverse'] },
  { id: 6, name: 'animationDuration', options: ['value'] },
  { id: 7, name: 'animationFillMode', options: ['none', 'forwards', 'backwards', 'both'] },
  { id: 8, name: 'animationIterationCount', options: ['value', 'infinite'] },
  { id: 9, name: 'animationName', options: ['value'] },
  { id: 10, name: 'animationPlayState', options: ['running', 'paused'] },
  {
    id: 11,
    name: 'animationTimingFunction',
    options: ['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out', 'step-start', 'step-end'],
  },
  { id: 12, name: 'backfaceVisibility', options: ['visible', 'hidden'] },
  { id: 13, name: 'backgroundColor', options: ['value'] },
  { id: 14, name: 'backgroundImage', options: ['value'] },
  { id: 15, name: 'backgroundPosition', options: ['value'] },
  { id: 16, name: 'backgroundRepeat', options: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat'] },
  { id: 17, name: 'backgroundAttachment', options: ['scroll', 'fixed', 'local'] },
  { id: 18, name: 'backgroundClip', options: ['border-box', 'padding-box', 'content-box', 'text'] },
  { id: 19, name: 'backgroundOrigin', options: ['border-box', 'padding-box', 'content-box'] },
  { id: 20, name: 'backgroundSize', options: ['auto', 'cover', 'contain'] },
  { id: 21, name: 'blockSize', options: ['value', 'auto'] },
  { id: 22, name: 'borderCollapse', options: ['collapse', 'separate'] },
  { id: 23, name: 'borderColor', options: ['value'] },
  { id: 24, name: 'borderImage', options: ['value'] },
  { id: 25, name: 'borderImageOutset', options: ['value'] },
  { id: 26, name: 'borderImageRepeat', options: ['stretch', 'repeat', 'round'] },
  { id: 27, name: 'borderImageSlice', options: ['value'] },
  { id: 28, name: 'borderImageSource', options: ['value'] },
  { id: 29, name: 'borderImageWidth', options: ['value'] },
  { id: 30, name: 'borderRadius', options: ['value'] },
  {
    id: 31,
    name: 'borderStyle',
    options: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  },
  { id: 32, name: 'borderWidth', options: ['value', 'thin', 'medium', 'thick'] },
  { id: 33, name: 'bottom', options: ['value', 'auto'] },
  { id: 34, name: 'boxDecorationBreak', options: ['slice', 'clone'] },
  { id: 35, name: 'boxShadow', options: ['value'] },
  { id: 36, name: 'boxSizing', options: ['content-box', 'border-box'] },
  {
    id: 37,
    name: 'breakAfter',
    options: [
      'auto',
      'avoid',
      'always',
      'page',
      'left',
      'right',
      'recto',
      'verso',
      'avoid-page',
      'avoid-column',
    ],
  },
  {
    id: 38,
    name: 'breakBefore',
    options: [
      'auto',
      'avoid',
      'always',
      'page',
      'left',
      'right',
      'recto',
      'verso',
      'avoid-page',
      'avoid-column',
    ],
  },
  { id: 39, name: 'breakInside', options: ['auto', 'avoid', 'avoid-page', 'avoid-column'] },
  { id: 40, name: 'captionSide', options: ['top', 'bottom', 'left', 'right'] },
  { id: 41, name: 'caretColor', options: ['value'] },
  { id: 42, name: 'clear', options: ['none', 'left', 'right', 'both'] },
  { id: 43, name: 'clip', options: ['value'] },
  { id: 44, name: 'color', options: ['value'] },
  { id: 45, name: 'columnCount', options: ['value', 'auto'] },
  { id: 46, name: 'columnFill', options: ['auto', 'balance'] },
  { id: 47, name: 'columnGap', options: ['value', 'normal'] },
  { id: 48, name: 'columnRule', options: ['value'] },
  { id: 49, name: 'columnRuleColor', options: ['value'] },
  {
    id: 50,
    name: 'columnRuleStyle',
    options: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  },
  { id: 51, name: 'columnRuleWidth', options: ['value', 'thin', 'medium', 'thick'] },
  { id: 52, name: 'columnSpan', options: ['none', 'all'] },
  { id: 53, name: 'columnWidth', options: ['value', 'auto'] },
  { id: 54, name: 'columns', options: ['value', 'auto'] },
  {
    id: 55,
    name: 'content',
    options: [
      'normal',
      'none',
      'counter',
      'attr',
      'open-quote',
      'close-quote',
      'no-open-quote',
      'no-close-quote',
      'url',
      'linear-gradient',
      'radial-gradient',
      'repeating-linear-gradient',
      'repeating-radial-gradient',
    ],
  },
  { id: 56, name: 'counterIncrement', options: ['value'] },
  { id: 57, name: 'counterReset', options: ['value'] },
  { id: 58, name: 'cursor', options: ['value'] },
  { id: 59, name: 'direction', options: ['ltr', 'rtl'] },
  {
    id: 60,
    name: 'display',
    options: [
      'inline',
      'block',
      'contents',
      'flex',
      'grid',
      'inline-block',
      'inline-flex',
      'inline-grid',
      'inline-table',
      'list-item',
      'run-in',
      'table',
      'table-caption',
      'table-cell',
      'table-column',
      'table-column-group',
      'table-footer-group',
      'table-header-group',
      'table-row',
      'table-row-group',
      'none',
    ],
  },
  { id: 61, name: 'emptyCells', options: ['show', 'hide'] },
  { id: 62, name: 'filter', options: ['value'] },
  { id: 63, name: 'flex', options: ['value', 'none', 'auto', 'initial', 'inherit'] },
  { id: 64, name: 'flexBasis', options: ['value', 'auto'] },
  { id: 65, name: 'flexDirection', options: ['row', 'row-reverse', 'column', 'column-reverse'] },
  { id: 66, name: 'flexFlow', options: ['value'] },
  { id: 67, name: 'flexGrow', options: ['value', 'initial', 'inherit'] },
  { id: 68, name: 'flexShrink', options: ['value', 'initial', 'inherit'] },
  { id: 69, name: 'flexWrap', options: ['nowrap', 'wrap', 'wrap-reverse'] },
  { id: 70, name: 'float', options: ['none', 'left', 'right'] },
  { id: 71, name: 'font', options: ['value'] },
  { id: 72, name: 'fontFamily', options: ['value'] },
  { id: 74, name: 'fontKerning', options: ['auto', 'normal', 'none'] },
  {
    id: 75,
    name: 'fontSize',
    options: [
      'value',
      'xx-small',
      'x-small',
      'small',
      'medium',
      'large',
      'x-large',
      'xx-large',
      'larger',
      'smaller',
    ],
  },
  {
    id: 76,
    name: 'fontStretch',
    options: [
      'normal',
      'ultra-condensed',
      'extra-condensed',
      'condensed',
      'semi-condensed',
      'semi-expanded',
      'expanded',
      'extra-expanded',
      'ultra-expanded',
    ],
  },
  { id: 77, name: 'fontStyle', options: ['normal', 'italic', 'oblique'] },
  { id: 78, name: 'fontVariant', options: ['normal', 'small-caps'] },
  { id: 79, name: 'fontWeight', options: ['lighter', 'light', 'normal', 'bold', 'bolder'] },
  { id: 80, name: 'gap', options: ['value'] },
  { id: 81, name: 'grid', options: ['value'] },
  { id: 82, name: 'gridArea', options: ['value'] },
  {
    id: 83,
    name: 'gridAutoColumns',
    options: ['value', 'auto', 'max-content', 'min-content', 'fit-content'],
  },
  { id: 84, name: 'gridAutoFlow', options: ['row', 'column'] },
  { id: 85, name: 'gridAutoRows', options: ['value', 'auto', 'max-content', 'min-content', 'fit-content'] },
  { id: 86, name: 'gridColumn', options: ['value'] },
  { id: 87, name: 'gridColumnEnd', options: ['value'] },
  { id: 88, name: 'gridColumnGap', options: ['value'] },
  { id: 89, name: 'gridColumnStart', options: ['value'] },
  { id: 90, name: 'gridGap', options: ['value'] },
  { id: 91, name: 'gridRow', options: ['value'] },
  { id: 92, name: 'gridRowEnd', options: ['value'] },
  { id: 93, name: 'gridRowGap', options: ['value'] },
  { id: 94, name: 'gridRowStart', options: ['value'] },
  { id: 95, name: 'gridTemplate', options: ['value'] },
  { id: 96, name: 'gridTemplateAreas', options: ['value'] },
  { id: 97, name: 'gridTemplateColumns', options: ['value'] },
  { id: 98, name: 'gridTemplateRows', options: ['value'] },
  { id: 99, name: 'height', options: ['value', 'auto'] },
  { id: 100, name: 'hyphens', options: ['none', 'manual', 'auto'] },
  { id: 101, name: 'imageRendering', options: ['auto', 'crisp-edges', 'pixelated'] },
  { id: 102, name: 'inlineSize', options: ['value', 'auto'] },
  { id: 103, name: 'isolation', options: ['auto', 'isolate'] },
  {
    id: 104,
    name: 'justifyContent',
    options: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly'],
  },
  {
    id: 105,
    name: 'justifyItems',
    options: [
      'auto',
      'normal',
      'stretch',
      'center',
      'start',
      'end',
      'flex-start',
      'flex-end',
      'self-start',
      'self-end',
      'baseline',
    ],
  },
  {
    id: 106,
    name: 'justifySelf',
    options: [
      'auto',
      'normal',
      'stretch',
      'center',
      'start',
      'end',
      'flex-start',
      'flex-end',
      'self-start',
      'self-end',
      'baseline',
    ],
  },
  { id: 107, name: 'left', options: ['value', 'auto'] },
  { id: 108, name: 'letterSpacing', options: ['value', 'normal'] },
  { id: 109, name: 'lineBreak', options: ['auto', 'loose', 'normal', 'strict'] },
  { id: 110, name: 'lineHeight', options: ['value', 'normal'] },
  { id: 111, name: 'listStyle', options: ['value'] },
  { id: 112, name: 'listStyleImage', options: ['value'] },
  { id: 113, name: 'listStylePosition', options: ['inside', 'outside'] },
  {
    id: 114,
    name: 'listStyleType',
    options: [
      'disc',
      'circle',
      'square',
      'decimal',
      'decimal-leading-zero',
      'lower-roman',
      'upper-roman',
      'lower-greek',
      'lower-alpha',
    ],
  },
  { id: 115, name: 'margin', options: ['value'] },
  { id: 116, name: 'marginBlockEnd', options: ['value', 'auto'] },
  { id: 117, name: 'marginBlockStart', options: ['value', 'auto'] },
  { id: 118, name: 'marginBottom', options: ['value', 'auto'] },
  { id: 119, name: 'marginInlineEnd', options: ['value', 'auto'] },
  { id: 120, name: 'marginInlineStart', options: ['value', 'auto'] },
  { id: 121, name: 'marginLeft', options: ['value', 'auto'] },
  { id: 122, name: 'marginRight', options: ['value', 'auto'] },
  { id: 123, name: 'marginTop', options: ['value', 'auto'] },
  { id: 124, name: 'marker', options: ['value'] },
  { id: 125, name: 'mask', options: ['value'] },
  { id: 126, name: 'maskType', options: ['alpha', 'luminance'] },
  { id: 127, name: 'maxBlockSize', options: ['value', 'none'] },
  { id: 128, name: 'maxHeight', options: ['value', 'none'] },
  { id: 129, name: 'maxInlineSize', options: ['value', 'none'] },
  { id: 130, name: 'maxWidth', options: ['value', 'none'] },
  { id: 131, name: 'minBlockSize', options: ['value', 'auto'] },
  { id: 132, name: 'minHeight', options: ['value', 'auto'] },
  { id: 133, name: 'minInlineSize', options: ['value', 'auto'] },
  { id: 134, name: 'minWidth', options: ['value', 'auto'] },
  {
    id: 135,
    name: 'mixBlendMode',
    options: [
      'normal',
      'multiply',
      'screen',
      'overlay',
      'darken',
      'lighten',
      'color-dodge',
      'color-burn',
      'hard-light',
      'soft-light',
      'difference',
      'exclusion',
      'hue',
      'saturation',
      'color',
      'luminosity',
    ],
  },
  { id: 136, name: 'objectFit', options: ['fill', 'contain', 'cover', 'none', 'scale-down'] },
  { id: 137, name: 'objectPosition', options: ['value'] },
  { id: 138, name: 'offset', options: ['value'] },
  { id: 139, name: 'offsetDistance', options: ['value'] },
  { id: 140, name: 'offsetPath', options: ['value'] },
  { id: 141, name: 'offsetRotate', options: ['value', 'auto'] },
  { id: 142, name: 'opacity', options: ['value'] },
  { id: 143, name: 'order', options: ['value', 'initial', 'inherit'] },
  { id: 144, name: 'orientation', options: ['auto', 'landscape', 'portrait'] },
  { id: 145, name: 'orphans', options: ['value'] },
  { id: 146, name: 'outline', options: ['value'] },
  { id: 147, name: 'outlineColor', options: ['value'] },
  { id: 148, name: 'outlineOffset', options: ['value'] },
  {
    id: 149,
    name: 'outlineStyle',
    options: ['none', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  },
  { id: 150, name: 'outlineWidth', options: ['value', 'thin', 'medium', 'thick'] },
  { id: 151, name: 'overflow', options: ['visible', 'hidden', 'scroll', 'auto'] },
  { id: 152, name: 'overflowAnchor', options: ['none', 'auto'] },
  { id: 153, name: 'overflowWrap', options: ['normal', 'break-word'] },
  { id: 154, name: 'overflowX', options: ['visible', 'hidden', 'scroll', 'auto'] },
  { id: 155, name: 'overflowY', options: ['visible', 'hidden', 'scroll', 'auto'] },
  { id: 156, name: 'overscrollBehavior', options: ['auto', 'contain', 'none'] },
  { id: 157, name: 'overscrollBehaviorBlock', options: ['auto', 'contain', 'none'] },
  { id: 158, name: 'overscrollBehaviorInline', options: ['auto', 'contain', 'none'] },
  { id: 159, name: 'overscrollBehaviorX', options: ['auto', 'contain', 'none'] },
  { id: 160, name: 'overscrollBehaviorY', options: ['auto', 'contain', 'none'] },
  { id: 161, name: 'padding', options: ['value'] },
  { id: 162, name: 'paddingBlockEnd', options: ['value'] },
  { id: 163, name: 'paddingBlockStart', options: ['value'] },
  { id: 164, name: 'paddingBottom', options: ['value'] },
  { id: 165, name: 'paddingInlineEnd', options: ['value'] },
  { id: 166, name: 'paddingInlineStart', options: ['value'] },
  { id: 167, name: 'paddingLeft', options: ['value'] },
  { id: 168, name: 'paddingRight', options: ['value'] },
  { id: 169, name: 'paddingTop', options: ['value'] },
  { id: 170, name: 'page', options: ['value'] },
  { id: 171, name: 'pageBreakAfter', options: ['auto', 'always', 'avoid', 'left', 'right'] },
  { id: 172, name: 'pageBreakBefore', options: ['auto', 'always', 'avoid', 'left', 'right'] },
  { id: 173, name: 'pageBreakInside', options: ['auto', 'avoid'] },
  { id: 174, name: 'paintOrder', options: ['normal', 'fill', 'stroke', 'markers'] },
  { id: 175, name: 'perspective', options: ['value'] },
  { id: 176, name: 'perspectiveOrigin', options: ['value'] },
  { id: 177, name: 'placeContent', options: ['value'] },
  { id: 178, name: 'placeItems', options: ['value'] },
  { id: 179, name: 'placeSelf', options: ['auto', 'normal', 'stretch'] },
  { id: 181, name: 'position', options: ['static', 'relative', 'absolute', 'fixed', 'sticky'] },
  { id: 182, name: 'quotes', options: ['value'] },
  { id: 183, name: 'resize', options: ['none', 'both', 'horizontal', 'vertical'] },
  { id: 184, name: 'right', options: ['value', 'auto'] },
  { id: 185, name: 'rotate', options: ['value'] },
  { id: 215, name: 'scrollSnapStop', options: ['normal', 'always'] },
  { id: 216, name: 'scrollSnapType', options: ['none', 'mandatory', 'proximity'] },
  { id: 217, name: 'scrollbarColor', options: ['auto', 'dark', 'light'] },
  { id: 218, name: 'scrollbarGutter', options: ['auto'] },
  { id: 219, name: 'scrollbarWidth', options: ['auto', 'thin', 'none'] },
  { id: 220, name: 'shapeImageThreshold', options: ['value'] },
  { id: 221, name: 'shapeOutside', options: ['value'] },
  {
    id: 222,
    name: 'shapeRendering',
    options: ['auto', 'optimizeSpeed', 'crispEdges', 'geometricPrecision'],
  },
  { id: 223, name: 'size', options: ['value', 'auto'] },
  {
    id: 224,
    name: 'speak',
    options: ['none', 'normal', 'spell-out', 'digits', 'literal-punctuation', 'no-punctuation'],
  },
  { id: 225, name: 'src', options: ['value'] },
  { id: 226, name: 'shapeMargin', options: ['value'] },
  { id: 227, name: 'tabSize', options: ['value'] },
  { id: 228, name: 'tableLayout', options: ['auto', 'fixed'] },
  {
    id: 229,
    name: 'textAlign',
    options: ['left', 'right', 'center', 'justify', 'justify-all', 'start', 'end', 'match-parent'],
  },
  {
    id: 230,
    name: 'textAlignLast',
    options: ['auto', 'start', 'end', 'left', 'right', 'center', 'justify'],
  },
  { id: 231, name: 'textCombineUpright', options: ['none', 'all', 'digits'] },
  { id: 232, name: 'textDecoration', options: ['none', 'underline', 'overline', 'line-through', 'blink'] },
  { id: 233, name: 'textDecorationColor', options: ['value'] },
  { id: 234, name: 'textDecorationLine', options: ['none', 'underline', 'overline', 'line-through'] },
  { id: 235, name: 'textDecorationStyle', options: ['solid', 'double', 'dotted', 'dashed', 'wavy'] },
  { id: 236, name: 'textIndent', options: ['value'] },
  { id: 237, name: 'textJustify', options: ['auto', 'none', 'inter-word', 'inter-character'] },
  { id: 238, name: 'textOrientation', options: ['mixed', 'upright', 'sideways', 'sideways-right'] },
  { id: 239, name: 'textOverflow', options: ['clip', 'ellipsis'] },
  {
    id: 240,
    name: 'textRendering',
    options: ['auto', 'optimizeSpeed', 'optimizeLegibility', 'geometricPrecision'],
  },
  { id: 241, name: 'textShadow', options: ['value'] },
  {
    id: 242,
    name: 'textTransform',
    options: ['none', 'capitalize', 'uppercase', 'lowercase', 'full-width'],
  },
  { id: 243, name: 'textUnderlinePosition', options: ['auto', 'under', 'left', 'right'] },
  { id: 244, name: 'top', options: ['value', 'auto'] },
  {
    id: 245,
    name: 'touchAction',
    options: [
      'auto',
      'none',
      'pan-x',
      'pan-left',
      'pan-right',
      'pan-y',
      'pan-up',
      'pan-down',
      'manipulation',
    ],
  },
  { id: 246, name: 'transform', options: ['value'] },
  { id: 247, name: 'transformBox', options: ['border-box', 'fill-box', 'view-box'] },
  { id: 248, name: 'transformOrigin', options: ['value'] },
  { id: 249, name: 'transformStyle', options: ['flat', 'preserve-3d'] },
  { id: 250, name: 'transition', options: ['value'] },
  { id: 251, name: 'transitionDelay', options: ['value'] },
  { id: 252, name: 'transitionDuration', options: ['value'] },
  { id: 253, name: 'transitionProperty', options: ['none', 'all'] },
  { id: 254, name: 'transitionTimingFunction', options: ['ease'] },
  { id: 276, name: 'whiteSpace', options: ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line'] },
  { id: 277, name: 'widows', options: ['value'] },
  { id: 278, name: 'width', options: ['value', 'auto'] },
  { id: 279, name: 'willChange', options: ['auto', 'scroll-position', 'contents', 'transform', 'opacity'] },
  { id: 280, name: 'wordBreak', options: ['normal', 'break-all', 'keep-all'] },
  { id: 281, name: 'wordSpacing', options: ['value'] },
  { id: 282, name: 'wordWrap', options: ['normal', 'break-word'] },
  {
    id: 283,
    name: 'writingMode',
    options: ['horizontal-tb', 'vertical-rl', 'vertical-lr', 'sideways-rl', 'sideways-lr'],
  },
  { id: 284, name: 'zIndex', options: ['value', 'auto'] },
  { id: 285, name: 'zoom', options: ['value'] },
]
